In [2]:
import numpy as np
from sipbuild.generator.parser.annotations import string

Numpy kütüphanesi bize python dilinde çalışan ve gayet hızlı bir işlem gücü sağlayan matematiksel kütüphanedir. Burada numpy kütüphanesinin özelliklerine değineceğiz.

# Numpy Arrays
Numpy arraylar *tek tip veri* alır. Numpy arraylerin üzerinde tanımlı bir sürü işlem yapılabilir. Bu arraylar üzerinde matematiksel operatörler tanımlıdır. Ayrıca numpy arraylerin built-in bir çok property'si de vardır. Mesela shape propertysi vardır. Bu ilgili dizinin yapısı hakkında bize bilgi verir. .shape[0] bize dizinin boyutunu verir.

In [52]:
xx = np.array([12, "Tahiri"]) # Sıkıntılı
arr_test = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12])
print(xx) # Görüldüğü üzere numpy arrayler tek tip olabilir. Yukarıda xx'i karışık vermiş olsak bile arka planda bunlar tek bir veri tipine dönüştürüldü!!!.

x_train = np.array([1.0, 2.0]) #numpy arraye dönüşüm
y_train = np.array([300.0, 500.0]) 
print(f"x_train shape: {x_train.shape}")
m = x_train.shape[0]
print(f"x_train length is: {m}")

k = 0
print(f"1. training example of x feature: {x_train[0]}")
print(f"1. training example of y output: {y_train[0]}")

['12' 'Tahiri']
x_train shape: (2,)
x_train length is: 2
1. training example of x feature: 1.0
1. training example of y output: 300.0


### Numpy array üzerinde random ve zeros

In [47]:
print(f"Numpy arrayin şekli: {arr_test.shape}")
print(f"Sadece sıfırlardan olşan bir nump dizisi: {np.zeros(10)}") #parametre olrak aldığı değer boyutunu belirtir.
print(f"Random sayılardan oluşan numpy dizisi: {np.random.random_sample(5)}") # [0,1) arasında rastgele sayı üretir.

# np.arange([başlangıç], bitiş, [adım], [dtype])
print(f"Belli bir değere kadar tam sayı üreten fonksiyon: {np.arange(0,10,3,float)}")

# Aritematik işlemler
print(f"Numpy array: {arr_test}")
print(f"Numpy array negatives: {-1 * arr_test}")
print(f"Numpy array sum: {np.sum(arr_test)}")
print(f"Numpy array değerleri ortalaması: {np.mean(arr_test)}")
print(f"Numpy array üs alma işlemi: {arr_test ** 3}")


Numpy arrayin şekli: (13,)
Sadece sıfırlardan olşan bir nump dizisi: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Random sayılardan oluşan numpy dizisi: [0.65902423 0.01042624 0.82425113 0.40729091 0.3847128 ]
Belli bir değere kadar tam sayı üreten fonksiyon: [0. 3. 6. 9.]
Numpy array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12]
Numpy array negatives: [  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12]
Numpy array sum: 78
Numpy array değerleri ortalaması: 6.0
Numpy array üs alma işlemi: [   0    1    8   27   64  125  216  343  512  729 1000 1331 1728]


Şimdi lineer cebir konusu olan matrix çarpımına gelelim. Aslında 2 tane vektörün çarpımıdır. Tek boyutlu vektorler için gayet basit bir işlem yapılır.

### Vectorler
Aslında bir boytulu bir dizi 1-D vectordür. Numpy arrayleri sayesinde vectorler üzerinde rahatça işlem yapabiliriz. 1-D vectorlerin birleşmesi ile de matrixler oluşur. Yani 2-D bir vector aslında bir matrixtir. Genelde sadece bir boyurlu yapılar için vector kavramı kullanılır.

In [51]:
vector_1 = np.random.rand(4) * 3 + 1
vector_2 = np.random.rand(4) * 3 + 1

print(vector_1)
print(vector_2)

print(f"2 vectorün çarpım sonucu: {np.dot(vector_1, vector_2)}")

[1.98107054 3.17727784 2.30965962 1.55723682]
[1.92479446 2.39344614 2.97524301 1.99281725]
2 vectorün çarpım sonucu: 21.392884002395846


### Matris İşlemleri

In [61]:
matrix_1 = [[1,2,3],[10,20,30],[100,200,300]]
matrix_2 = np.zeros((2,5))

print(matrix_1)
print(f"Matrix_2: {matrix_2}")
matrix_2 = np.random.randn(2,5)
print(f"Matrix_2 with random numbers: {matrix_2}")

[[1, 2, 3], [10, 20, 30], [100, 200, 300]]
Matrix_2: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Matrix_2 with random numbers: [[-0.73614011  1.65532605  1.5004773  -0.03872763  0.52595034]
 [ 1.41960669 -0.22337238  1.7370417  -1.92821079 -0.05197788]]


### Indexing and Slicing
Aşağıda bazı indeksleme ve slicing işlemleri gösterilecektir.

In [78]:
matrix_2 = matrix_2.reshape(5,2) #Bi aşt satırdaki kod ile aynı anlamı ifade eder.
matrix_2 = matrix_2.reshape(2, -1) #reshape fonksiyonu matrix oluşturmanın rahat bir yoludur.
print(matrix_2)

print(f"2.satır 1.sutün: {matrix_2[1,0]}")
print(f"Matrixin 4.satırı: {matrix_2[1]}")

#Slicing

print(f"matrix_2 1.satırı üzerinde slice işlemi: {matrix_2[0, 1:4:1]}")

[[-0.73614011  1.65532605  1.5004773  -0.03872763  0.52595034]
 [ 1.41960669 -0.22337238  1.7370417  -1.92821079 -0.05197788]]
2.satır 1.sutün: 1.4196066859564866
Matrixin 4.satırı: [ 1.41960669 -0.22337238  1.7370417  -1.92821079 -0.05197788]
matrix_2 1.satırı üzerinde slice işlemi: [ 1.65532605  1.5004773  -0.03872763]


In [10]:
np.array(matrixListesi)

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

=> bu şekilde bir görünüm elde etmesi işimize gelir.

# arange

In [11]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

=> numpy kütüphanesinde bulunan arange metodunu kullanarak da bir dizi oluşturabiliriz

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

# zeros-ones

In [14]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

bize belirtilen sayı kadar 0 döner

In [16]:
np.zeros((10,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

=> matrix şeklinde de tanımlanabilir.

In [17]:
np.ones(3)

array([1., 1., 1.])

=> bu metodda basit bir şekilde 1 oluşturur.

# linspace

In [22]:
np.linspace(0,13,3)

array([ 0. ,  6.5, 13. ])

In [26]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

=> bu metot bize ilgili sayılar arasında, belirtilen sayı kadar sayı seçer. Ancak bu seçme işlemini yaparken seçilen sayıların arasındaki farkın eşit olmasını sağlar.

# eye

In [29]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

=> çaprazı 1 ile dolu olan bir matriks hazrılar.

# random

In [32]:
np.random.randn(9)

array([ 1.65448134,  0.60104974,  1.00441216,  0.20188044,  0.28229187,
        0.24031622,  0.37234169,  1.70054648, -2.27260234])

=> belirtilen sayı kadar rastgele değer üretir.

In [33]:
np.random.randn(3,4)

array([[-1.61460863, -0.3403926 , -0.80755765,  0.90907169],
       [-0.8041096 ,  0.65004378, -0.64735653, -0.29746658],
       [-0.819737  , -0.00777323, -0.3802361 , -0.38002017]])

In [42]:
np.random.randint(0,20,10)

array([15,  6, 12, 12,  3, 11, 10,  8, 10,  5])

=> buda sadece int değerleri döndürür. Sonda verilen sayı ne kadar rastgele sayı istediğimizi belirtir.

In [49]:
listem = np.random.randint(1,300,30)

In [50]:
listem

array([140,  84, 151,   8, 194, 218, 235, 167, 149,  77,  46, 145,  85,
       160,  32,  50, 224, 277, 251,  19,  29, 286, 159,  29, 127, 107,
       215,  90, 130, 272])

# numpy array methods

In [51]:
listem.reshape(6,5)

array([[140,  84, 151,   8, 194],
       [218, 235, 167, 149,  77],
       [ 46, 145,  85, 160,  32],
       [ 50, 224, 277, 251,  19],
       [ 29, 286, 159,  29, 127],
       [107, 215,  90, 130, 272]])

=> reshape metodu ile diziyi yeniden şekillendirebiliyoruz ama şekillendirmek istediğimiz dizinin boyutu, metot parametreleri uyumlu olmalıdır. Yani 30 boyutlu bir dizi varsa elimizde onu matrix haline getirirken boyutunu dikkate almamız gerekir.

In [53]:
listem.max()

286

=> bu şekilde, rastgele oluşturulmuş bir diziinin max ve min deeğrlerine rahatlıkla ulaşabilir.

In [54]:
type(listem)

numpy.ndarray

In [55]:
listem.min()

8

In [56]:
listem.argmax()

21

=> max değerinin dizinin hangi indexinde bulunduğunu gösterir.

In [63]:
reshapeListem = listem.reshape(3,10)

In [66]:
reshapeListem.shape

(3, 10)

=> dizinin hangi şekle sahip olduğunu gösterir.

# indexleme-operayonlar

In [67]:
dizim = np.arange(0,15)

In [68]:
dizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [70]:
dizim[5]

5

In [74]:
dizim[3:8]

array([3, 4, 5, 6, 7])

In [75]:
dizim[3:8] = 2

In [76]:
dizim

array([ 0,  1,  2,  2,  2,  2,  2,  2,  8,  9, 10, 11, 12, 13, 14])

In [88]:
dizim = np.arange(0,20)

In [89]:
dizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [90]:
dizi = dizim[4:9]

=> burada referans ataması yapıyor. Bunu unutmamak lazım. Yani şuan dizi üzerinde değişiklik yaparsam dizim üzerinde de değişiklik yapmış olacağım.

In [91]:
dizi

array([4, 5, 6, 7, 8])

In [93]:
dizi[:] = 700

In [94]:
dizi

array([700, 700, 700, 700, 700])

In [95]:
dizim

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

=> numpy dizilerinde atama işlemlerince c# da ki gibi davranıyor.

In [96]:
yeniDizi = dizim.copy()

In [97]:
yeniDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [98]:
dizim

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [99]:
yeniDizi[:] = 0

In [100]:
yeniDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [101]:
dizim

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

=> görüldüğü üzeri copy metodu kullanrak deep copy yapılabilir.

# matrixler

In [107]:
ornekMatrix = np.array([[1,2,3],[10,20,30],[100,200,300],[1000,2000,3000],[50,60,80]])

In [108]:
ornekMatrix

array([[   1,    2,    3],
       [  10,   20,   30],
       [ 100,  200,  300],
       [1000, 2000, 3000],
       [  50,   60,   80]])

In [109]:
ornekMatrix[0]

array([1, 2, 3])

In [110]:
ornekMatrix[0,1]

2

In [112]:
ornekMatrix[0][1]

2

görüldüğü üzere iki türlü de iki boyutlu dizilere yani matrixlere erişim sağlayabiliyoruz

In [119]:
ornekMatrix[1:3,2]

array([ 30, 300])

In [120]:
ornekMatrix[1:,2]

array([  30,  300, 3000,   80])

In [123]:
ornekMatrix[1:,0:]

array([[  10,   20,   30],
       [ 100,  200,  300],
       [1000, 2000, 3000],
       [  50,   60,   80]])

In [125]:
ornekMatrix[[0,2,4],1:]

array([[  2,   3],
       [200, 300],
       [ 60,  80]])

In [126]:
ornekMatrix[::2,1:]

array([[  2,   3],
       [200, 300],
       [ 60,  80]])

# operasyonlar

In [130]:
myDizim = np.random.randint(20,1090,70)

In [131]:
myDizim

array([ 147,  453,  615,  176,  396,  226,  978,  497,  119,  738,  911,
        800,  841,  736,   44,  941,  839,  384,   38,  261,  262,  942,
        979,  423,  863,  129,  185,  249,  222,  464,  927,  725,  469,
        706,  729,  696,  402, 1072,  850,  805,  428,  879,  166,  638,
        608,  689,  218,  506,  417,  333,  316, 1058,  941,  766,  119,
        860,  897,  502,  383,  153,  414,  674,  526,  976,   86,  371,
       1051,  719,  541,  784])

In [132]:
myDizim > 70

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

=> bu şekilde bir operatör kullanrak dizinin hangi indexlerinin belirtilen değerden büyük olduğunu görebiliriz.

In [133]:
myDizim

array([ 147,  453,  615,  176,  396,  226,  978,  497,  119,  738,  911,
        800,  841,  736,   44,  941,  839,  384,   38,  261,  262,  942,
        979,  423,  863,  129,  185,  249,  222,  464,  927,  725,  469,
        706,  729,  696,  402, 1072,  850,  805,  428,  879,  166,  638,
        608,  689,  218,  506,  417,  333,  316, 1058,  941,  766,  119,
        860,  897,  502,  383,  153,  414,  674,  526,  976,   86,  371,
       1051,  719,  541,  784])

In [136]:
myDizim[myDizim < 90]

array([44, 38, 86])

bu şekilde bir syntax yapar isek o zaman da bize ilgili değerleri döndürecektir.

In [138]:
myDizim + 2

array([ 149,  455,  617,  178,  398,  228,  980,  499,  121,  740,  913,
        802,  843,  738,   46,  943,  841,  386,   40,  263,  264,  944,
        981,  425,  865,  131,  187,  251,  224,  466,  929,  727,  471,
        708,  731,  698,  404, 1074,  852,  807,  430,  881,  168,  640,
        610,  691,  220,  508,  419,  335,  318, 1060,  943,  768,  121,
        862,  899,  504,  385,  155,  416,  676,  528,  978,   88,  373,
       1053,  721,  543,  786])

In [139]:
myDizim * 2

array([ 294,  906, 1230,  352,  792,  452, 1956,  994,  238, 1476, 1822,
       1600, 1682, 1472,   88, 1882, 1678,  768,   76,  522,  524, 1884,
       1958,  846, 1726,  258,  370,  498,  444,  928, 1854, 1450,  938,
       1412, 1458, 1392,  804, 2144, 1700, 1610,  856, 1758,  332, 1276,
       1216, 1378,  436, 1012,  834,  666,  632, 2116, 1882, 1532,  238,
       1720, 1794, 1004,  766,  306,  828, 1348, 1052, 1952,  172,  742,
       2102, 1438, 1082, 1568])

In [140]:
fDizi = myDizim

In [141]:
fDizi * myDizim

array([  21609,  205209,  378225,   30976,  156816,   51076,  956484,
        247009,   14161,  544644,  829921,  640000,  707281,  541696,
          1936,  885481,  703921,  147456,    1444,   68121,   68644,
        887364,  958441,  178929,  744769,   16641,   34225,   62001,
         49284,  215296,  859329,  525625,  219961,  498436,  531441,
        484416,  161604, 1149184,  722500,  648025,  183184,  772641,
         27556,  407044,  369664,  474721,   47524,  256036,  173889,
        110889,   99856, 1119364,  885481,  586756,   14161,  739600,
        804609,  252004,  146689,   23409,  171396,  454276,  276676,
        952576,    7396,  137641, 1104601,  516961,  292681,  614656])

Bu şekilde diziler içinde operatör kullanabiliyoruz.

In [142]:
np.sqrt(fDizi)

array([12.12435565, 21.28379665, 24.79919354, 13.26649916, 19.89974874,
       15.03329638, 31.27299154, 22.29349681, 10.90871211, 27.16615541,
       30.18277655, 28.28427125, 29.        , 27.12931993,  6.63324958,
       30.6757233 , 28.96549672, 19.59591794,  6.164414  , 16.15549442,
       16.18641406, 30.69201851, 31.28897569, 20.5669638 , 29.37686164,
       11.35781669, 13.60147051, 15.77973384, 14.89966443, 21.54065923,
       30.4466747 , 26.92582404, 21.65640783, 26.57066051, 27.        ,
       26.38181192, 20.04993766, 32.74141109, 29.15475947, 28.37252192,
       20.68816087, 29.64793416, 12.88409873, 25.25866188, 24.65765601,
       26.2488095 , 14.76482306, 22.49444376, 20.42057786, 18.24828759,
       17.77638883, 32.52691193, 30.6757233 , 27.67670501, 10.90871211,
       29.3257566 , 29.94995826, 22.4053565 , 19.57038579, 12.36931688,
       20.34698995, 25.96150997, 22.93468988, 31.2409987 ,  9.2736185 ,
       19.26136028, 32.41913015, 26.81417536, 23.2594067 , 28.  

=> Karekök alma bile yapabiliriz!